function onCreate()
    setProperty('gf.visible', false)
    makeLuaSprite('sky', 'bgs/emerald altar/sky', -1227, -372)
    setScrollFactor('sky', 0.1, 0.3)
    scaleObject('sky', 2,2)
    addLuaSprite('sky', false)

    makeLuaSprite('mountains1', 'bgs/emerald altar/bgmountain1', 1124, -134)
    setScrollFactor('mountains1', 0.5, 0.6)
    addLuaSprite('mountains1', false)
    makeLuaSprite('mountains2', 'bgs/emerald altar/bgmountain2', -904, -224)
    setScrollFactor('mountains2', 0.5, 0.6)
    addLuaSprite('mountains2', false)
    scaleObject('mountains1', 2,2)
    scaleObject('mountains2', 2,2)

    makeLuaSprite('bushes', 'bgs/emerald altar/bushes', -939, 215)
    setScrollFactor('bushes', 0.6, 0.9)
    addLuaSprite('bushes', false)
    scaleObject('bushes', 2,2)

    makeLuaSprite('tree1', 'bgs/emerald altar/tree1', -468, 257)
    setScrollFactor('tree1', 0.7, 0.9)
    setProperty('tree1.flipX', true)
    scaleObject('tree1', 2,2)
    addLuaSprite('tree1', false)

    makeLuaSprite('tree2', 'bgs/emerald altar/tree1', -738, 282)
    setScrollFactor('tree2', 0.7, 0.9)
    setProperty('tree2.flipX', true)
    addLuaSprite('tree2', false)
    scaleObject('tree2', 2,2)

    makeLuaSprite('tree3', 'bgs/emerald altar/tree2', -275, 344)
    setScrollFactor('tree3', 0.7, 0.9)
    setProperty('tree3.flipX', true)
    scaleObject('tree3', 2,2)
    addLuaSprite('tree3', false)

    makeLuaSprite('tree4', 'bgs/emerald altar/tree1', 1647, 272)
    setScrollFactor('tree4', 0.7, 0.9)
    scaleObject('tree4', 2,2)
    addLuaSprite('tree4', false)

    makeLuaSprite('tree5', 'bgs/emerald altar/tree2', 1845, 384)
    setScrollFactor('tree5', 0.7, 0.9)
    scaleObject('tree5', 2,2)
    addLuaSprite('tree5', false)

    makeAnimatedLuaSprite('eggman', 'bgs/emerald altar/eggman', -440, -60)
    addAnimationByPrefix('eggman', 'idle', 'eggman idle', 24, false)
    setScrollFactor('eggman', 0.7, 0.9)
    scaleObject('eggman', 2,2)
	addLuaSprite('eggman')
    setProperty('eggman.visible', false)

    -- Pillars
    makeLuaSprite('pillar2', 'bgs/emerald altar/pillar4', 1158, 346)
    setScrollFactor('pillar2', 0.8, 1)
    scaleObject('pillar2', 2,2)
    addLuaSprite('pillar2', false)

    makeLuaSprite('pillar1', 'bgs/emerald altar/pillar3', -337, 359)
    setScrollFactor('pillar1', 0.8, 1)
    scaleObject('pillar1', 2,2)
    addLuaSprite('pillar1', false)

    makeLuaSprite('pillar2', 'bgs/emerald altar/pillar2', 843, 96)
    setScrollFactor('pillar2', 0.85, 0.85)
    scaleObject('pillar2', 2,2)
    addLuaSprite('pillar2', false)

    makeLuaSprite('pillar3', 'bgs/emerald altar/pillar1', 172, -29)
    setScrollFactor('pillar3', 0.8, 1)
    scaleObject('pillar3', 2,2)
    addLuaSprite('pillar3', false)

    makeLuaSprite('pillar4', 'bgs/emerald altar/pillar1', 992, -29)
    setProperty('pillar4.flipX', true)
    setScrollFactor('pillar4', 0.9, 0.9)
    scaleObject('pillar4', 2,2)
    addLuaSprite('pillar4', false)

    makeLuaSprite('masteremerald', 'bgs/emerald altar/emerald', 453, 21)
    addLuaSprite('masteremerald', false)
    scaleObject('masteremerald', 2,2)

    makeLuaSprite('altar', 'bgs/emerald altar/altar', -1470, 170)
    addLuaSprite('altar', false)
    scaleObject('altar', 2,2)

    makeAnimatedLuaSprite('rouge', 'bgs/emerald altar/rouge', 530, 250)
	addAnimationByIndices('rouge', 'danceLeft', 'rouge idle', '0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11', 24)
    addOffset('rouge', 'danceLeft', 0, 0)
	addAnimationByIndices('rouge', 'danceRight', 'rouge idle', '12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23', 24)
    addOffset('rouge', 'danceRight', 0, 0)
    addAnimationByPrefix('rouge', 'flying1', 'rouge flying', 24, true)
    addOffset('rouge', 'flying1', 0, 0)
    addAnimationByPrefix('rouge', 'land', 'rouge land', 24, false)
    addOffset('rouge', 'land', 10, 0)
    addAnimationByPrefix('rouge', 'liftoff', 'rouge liftoff', 24, false)
    addOffset('rouge', 'liftoff', -5, -25)
    addAnimationByPrefix('rouge', 'leaving', 'rouge leaving', 24, true)
    addOffset('rouge', 'leaving', 0, 0)
    scaleObject('rouge', 2,2)
	addLuaSprite('rouge')
end

function onCreatePost()
end
